name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    name: "Upload artifact"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          path: web-ext-artifacts/mastopinner-*.zip