name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    name: "Build and Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      
      - name: "Install npm"
        uses: actions/setup-node@v2
        with:
          node-version: 17
      
      - name: "Install eslint and web-ext"
        run: npm install --global eslint web-ext
      
      - name: "Build"
        run: |
          make all
          echo github.ref

      - name: "Release"
        uses: softprops/action-gh-release@v1
        with:
          files: web-ext-artifacts/mastopinner-*.zip
